# FrozenLake basic Q learning

In [17]:
import gym
import numpy as np
env = gym.make('FrozenLake-v0')

[2017-04-30 17:18:51,967] Making new env: FrozenLake-v0


In [21]:
num_states = env.observation_space.n
num_actions = env.action_space.n
learning_rate = 0.85
gamma = 0.99
num_episodes = 2000

In [30]:
#Initialize table with all zeros
Q = np.zeros([num_states,num_actions])
#create lists to contain total rewards and steps per episode
reward_list = []
count_list = []

In [26]:
for i in range(num_episodes):
    #Reset environment and get first new observation
    state = env.reset()
    All_reward = 0
    terminate_state = False
    count = 0
    #The Q-Table learning algorithm
    while count < 99:
        count+=1
        #Choose an action by greedily (with noise) picking from Q table
        random_factor = np.random.randn(1,num_actions)*(1./(i+1))
        action = np.argmax(Q[state,:] + random_factor)
        #Get new state and reward from environment
        state_prime,reward,terminate_state,_ = env.step(action)
        #Update Q-Table with new knowledge
        Q[state,action] = Q[state,action] + learning_rate*(reward + gamma*np.max(Q[state_prime,:]) - Q[state,action])
        All_reward += reward
        state = state_prime
        if terminate_state == True:
            break
    reward_list.append(All_reward)

In [28]:
print("Score over time: " +  str(sum(reward_list)/num_episodes))

Score over time: 0.7375


In [29]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.58947685e-02   1.59879519e-01   8.19791682e-03   1.18295465e-02]
 [  8.66036364e-03   1.27163090e-02   9.36279039e-03   9.83602221e-02]
 [  6.03407056e-03   1.19602607e-02   8.02911510e-03   8.50099408e-02]
 [  6.18323159e-06   1.99298088e-04   2.61245276e-02   8.55161351e-02]
 [  1.57407386e-01   1.53826493e-03   6.84397562e-04   1.23110385e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.44772351e-05   5.39584388e-05   9.93535126e-02   9.60495417e-06]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.60467626e-03   2.23940055e-03   7.04036187e-04   1.69116561e-01]
 [  5.89759676e-04   4.89531323e-01   2.45251825e-05   0.00000000e+00]
 [  2.43602780e-04   1.14949771e-04   1.77741058e-02   1.98433375e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.94136996e-05   2.86562811e-03   7.60179891e-01   3